import blogPlaceholder1 from '../assets/blog-placeholder-1.jpg';

export const projects = [
  {
    slug: 'retro-cd-player',
    title: 'Retro CD Player',
    year: 2025,
    category: 'UI/UX',
    shortDescription: 'A sleek, interactive CD player UI concept.',
    fullDescription: 'A modern web-based CD player inspired by retro-futuristic design, featuring tactile interactions and smooth transitions.',
    role: 'Designer & Developer',
    tools: ['Astro', 'TypeScript', 'CSS'],
    images: [blogPlaceholder1],
    cover: blogPlaceholder1,
    links: [{ label: 'Live Demo', url: '#' }, { label: 'GitHub', url: '#' }],
  },
  {
    slug: 'media-library',
    title: 'Media Library',
    year: 2024,
    category: 'Product Design',
    shortDescription: 'A curated digital media library experience.',
    fullDescription: 'A portfolio project showcasing a digital library with a physical media metaphor, using Astro and CSS for depth and interaction.',
    role: 'Lead Designer',
    tools: ['Astro', 'CSS Modules'],
    images: [blogPlaceholder1],
    cover: blogPlaceholder1,
    links: [{ label: 'Live Demo', url: '#' }, { label: 'GitHub', url: '#' }],
  },
  {
    slug: 'design-system',
    title: 'Design System',
    year: 2023,
    category: 'System',
    shortDescription: 'A robust design system for modern apps.',
    fullDescription: 'A scalable design system with reusable components, accessible patterns, and editorial typography.',
    role: 'System Architect',
    tools: ['Astro', 'TypeScript', 'Figma'],
    images: [blogPlaceholder1],
    cover: blogPlaceholder1,
    links: [{ label: 'Live Demo', url: '#' }, { label: 'GitHub', url: '#' }],
  },
  {
    slug: 'case-study-portfolio',
    title: 'Case Study Portfolio',
    year: 2022,
    category: 'Portfolio',
    shortDescription: 'A premium portfolio with case studies.',
    fullDescription: 'A portfolio site with detailed case studies, interactive visuals, and a tactile CD rack homepage.',
    role: 'Designer',
    tools: ['Astro', 'CSS', 'Motion One'],
    images: [blogPlaceholder1],
    cover: blogPlaceholder1,
    links: [{ label: 'Live Demo', url: '#' }, { label: 'GitHub', url: '#' }],
  },
];
// Add more projects by duplicating the object structure above.